### ISSUE TITLE
java-tron/build/libs/FullNode.jar’: No such file or directory

### ISSUE THREAD

**Issue by Abhishekoodles1** [tronprotocol/tron-deployment#13]
After running script` bash deploy_tron.sh`,  I am getting the error  " cannot stat  'FullNode/java-tron/build/libs/FullNode.jar’: No such file or directory.   when i go inside the 'java-tron/build/libs/' there is no FullNode.jar. Also when i tried to build project using ` ./gradlew build`. the error is coming 

`What went wrong:
Could not determine the dependencies of task ':buildKeystoreFactoryJar'.
> Could not resolve all files for configuration ':compile'.
   > Could not resolve org.apache.commons:commons-collections4:4.0.
     Required by:
         project :
      > Could not resolve org.apache.commons:commons-collections4:4.0.
         > Could not parse POM /home/abhishek/.m2/repository/org/apache/commons/commons-collections4/4.0/commons-collections4-4.0.pom
            > The processing instruction target matching "[xX][mM][lL]" is not allowed.
   > Could not resolve org.apache.commons:commons-lang3:3.4.
     Required by:
         project :
      > Could not resolve org.apache.commons:commons-lang3:3.4.
         > Could not parse POM /home/abhishek/.m2/repository/org/apache/commons/commons-lang3/3.4/commons-lang3-3.4.pom
            > Could not resolve org.apache.commons:commons-parent:37.
               > Could not resolve org.apache.commons:commons-parent:37.
                  > Could not parse POM /home/abhishek/.m2/repository/org/apache/commons/commons-parent/37/commons-parent-37.pom
                     > Content is not allowed in trailing section.

`
 
"

**Comment by shydesky** [comment]
you should check whether you can connect the maven central repo to fetch the dependencies
