### ISSUE TITLE
can't run FullNode.jar - org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'blockMsgHandler': Injection of autowired dependencies failed;

### ISSUE THREAD

**Issue by irth** [tronprotocol/tron-deployment#33]
I've downloaded the .jar from https://github.com/tronprotocol/java-tron/releases/download/Odyssey-v3.6.2/FullNode.jar and the config from https://raw.githubusercontent.com/tronprotocol/TronDeployment/master/main_net_config.conf

I'm trying to run it as `java -jar FullNode.jar -c main_net_config.conf` but it fails.

I've seen some issues with a similar exception but they didn't have any solutions, except one guy saying it started working on Oracle's Java, which sadly is not an option for me. What am I doing incorrectly? :)

```
❯ java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-b05)
OpenJDK 64-Bit Server VM (build 25.222-b05, mixed mode)
```

[tron.log](https://github.com/tronprotocol/tron-deployment/files/3546992/tron.log)

```
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'blockMsgHandler': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.TronNetDelegate org.tron.core.net.messagehandler.BlockMsgHandler.tronNetDelegate; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetDelegate': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.SyncPool org.tron.core.net.TronNetDelegate.syncPool; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'syncPool': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.discover.node.NodeManager org.tron.common.overlay.server.SyncPool.nodeManager; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nodeManager' defined in URL [jar:file:/home/me/code/tron/FullNode.jar!/org/tron/common/overlay/discover/node/NodeManager.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.tron.core.db.Manager]: : Error creating bean with name 'manager': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.TransactionStore org.tron.core.db.Manager.transactionStore; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionStore': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.KhaosDatabase org.tron.core.db.TransactionStore.khaosDatabase; nested exception is java.lang.NoClassDefFoundError: javafx/util/Pair; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'manager': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.TransactionStore org.tron.core.db.Manager.transactionStore; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionStore': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.KhaosDatabase org.tron.core.db.TransactionStore.khaosDatabase; nested exception is java.lang.NoClassDefFoundError: javafx/util/Pair
```

**Comment by shydesky** [comment]
> I've downloaded the .jar from https://github.com/tronprotocol/java-tron/releases/download/Odyssey-v3.6.2/FullNode.jar and the config from https://raw.githubusercontent.com/tronprotocol/TronDeployment/master/main_net_config.conf
> 
> I'm trying to run it as `java -jar FullNode.jar -c main_net_config.conf` but it fails.
> 
> I've seen some issues with a similar exception but they didn't have any solutions, except one guy saying it started working on Oracle's Java, which sadly is not an option for me. What am I doing incorrectly? :)
> 
> ```
> ❯ java -version
> openjdk version "1.8.0_222"
> OpenJDK Runtime Environment (build 1.8.0_222-b05)
> OpenJDK 64-Bit Server VM (build 25.222-b05, mixed mode)
> ```
> 
> [tron.log](https://github.com/tronprotocol/tron-deployment/files/3546992/tron.log)
> 
> ```
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'blockMsgHandler': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.net.TronNetDelegate org.tron.core.net.messagehandler.BlockMsgHandler.tronNetDelegate; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'tronNetDelegate': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.server.SyncPool org.tron.core.net.TronNetDelegate.syncPool; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'syncPool': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.common.overlay.discover.node.NodeManager org.tron.common.overlay.server.SyncPool.nodeManager; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nodeManager' defined in URL [jar:file:/home/me/code/tron/FullNode.jar!/org/tron/common/overlay/discover/node/NodeManager.class]: Unsatisfied dependency expressed through constructor argument with index 0 of type [org.tron.core.db.Manager]: : Error creating bean with name 'manager': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.TransactionStore org.tron.core.db.Manager.transactionStore; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionStore': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.KhaosDatabase org.tron.core.db.TransactionStore.khaosDatabase; nested exception is java.lang.NoClassDefFoundError: javafx/util/Pair; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'manager': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.TransactionStore org.tron.core.db.Manager.transactionStore; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionStore': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.tron.core.db.KhaosDatabase org.tron.core.db.TransactionStore.khaosDatabase; nested exception is java.lang.NoClassDefFoundError: javafx/util/Pair
> ```

yes, the OpenJDK is not supported perfectly right now. So you must replace the OpenJDK with Oracle JDK.

**Comment by irth** [comment]
Are there plans to support OpenJDK? Using Oracle's Java implementation was not possible in my case, unfortunately

**Comment by irth** [comment]
Are there plans to support OpenJDK? Using Oracle's Java implementation was not possible in my case, unfortunately

**Comment by CerberusGR** [comment]
irth did you find any solution?
