### ISSUE TITLE
I found that the configuration of test_net_config.conf is not the configuration node of shasta. 

### ISSUE THREAD

**Issue by apa7** [tronprotocol/tron-deployment#34]
I found that the configuration of test_net_config.conf is not the configuration node of shasta. 
For example, I query the hash of 84,289 height: 
  000000000001494160272893c41989f1137a09942a2b68a6dfc301b36b41c082
which is different from mainNet and shastaNet.

**Comment by apa7** [comment]
So how should the shasta seedNode be configured?

**Comment by shydesky** [comment]
> So how should the shasta seedNode be configured?

It is not supported to participate in the Shasta test network. The test_net_config.conf is the config of another test network which you can see here http://testnet.tronex.io/

**Comment by andelf** [comment]
Closed for no response for long.
Feel free to re-open or open-new.
