### ISSUE TITLE
javax annotation symbol not found

### ISSUE THREAD

**Issue by alirezaght** [tronprotocol/tron-deployment#36]
I'm using openjdk 11 and code doesn't compile. the error is cannot find symbol
@javax.annotation.Generated

After adding this line to dependencies in build.gradle file it compiled successfully
compile group: 'javax.annotation', name: 'javax.annotation-api', version: '1.3.2'

**Comment by Starsakary** [comment]
I'm sorry to leave this issue for a long time. Was it solved?

**Comment by jiangyy0824** [comment]
Please configure your develop enviroment according https://github.com/tronprotocol/java-tron/blob/develop/build.md.
This is caused by the jdk version. Thanks.
