### ISSUE TITLE
Quotes in the comment session for private_net or main_net  have  blocking the block production.(self Mining)

### ISSUE THREAD

**Issue by ravinayag** [tronprotocol/tron-deployment#46]
Hello, I able to launch the network  private_net  and the  main_net config file, I see two different outputs from the network launch logs. 
Steps to reproduce :
1,  Clone the java-tron repo and copy the main_net or private_net config file.
2, Compile the java-tron as per the readme file or https://developers.tron.network/docs/tron-private-chain  
3, copy the private_net config file and fullnode.jar under the new folder and  Start your SR node with the syntax given from the above link
`for ex. 
java -jar ./fullnode.jar --witness -c ./private_net.conf & 
tail logs/tron.log`

You will not see any block productivity in the logs.

Expected, Blocks to produce...self mining.

For self block producing, repeat the above steps, and before start follow the below steps.

Edit the config file with a favorite editor, remove the single quotes given in the text of commented lines. 
`for ex.  refer pic. `
If you are in VSC editor, it shows a difference when you remove the quote. because the single quote takes the rest of the remaining code as strings. So rest of the configurations are ignored.
![Uploading image.png…]()

 After this, if you run `java -jar ./fullnode.jar --witness -c ./private_net.conf & `
you will see the blocks are getting produced from the logs `tail logs/tron.log`

What I'm expecting is, Update the configuration files by removing the single quote on the text line or put # symbols.
How we can control the self mining in the networks. ? for ex. every 10 mins do self mining or every one hour or we can stop self mining. ..?

**Comment by Benson0224** [comment]
i just download the private_net_config.conf from:  https://github.com/tronprotocol/tron-deployment/blob/master/private_net_config.conf

simply started the super node with below command: 
` java -jar ./FullNode.jar --witness -c ./supernode_private_no_change.conf`

I can see it works on my side. it can produce blocks successfully.  see below screenshot:

Please make sure you are using Oracle JDK 8 and share the tron.log if you still see the issue, thanks

![image](https://user-images.githubusercontent.com/61768920/135383792-003e99a5-cfd4-4b02-b9c4-7e9939782900.png)

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
