### ISSUE TITLE
Testnet fails to start

### ISSUE THREAD

**Issue by ruanbekker** [tronprotocol/tron-deployment#48]
When attempting to start a Tron Fullnode on the Tesnet it fails with the following error:

```bash
$ java -Xmx2g -XX:+UseConcMarkSweepGC -jar FullNode.jar -c test_net_config.conf
Exception in thread "main" java.lang.IllegalArgumentException: The address() must be 21 bytes.
	at org.tron.common.args.Account.setAddress(Account.java:53)
	at org.tron.core.config.args.Args.createAccount(Args.java:851)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at org.tron.core.config.args.Args.getAccountsFromConfig(Args.java:844)
	at org.tron.core.config.args.Args.setParam(Args.java:391)
	at org.tron.program.FullNode.main(FullNode.java:54)
```

The testnet configuration was found from this github repo:
- https://github.com/tronprotocol/tron-deployment/blob/master/test_net_config.conf

The jar was downloaded from the 4.4.0 release:
- https://github.com/tronprotocol/java-tron/releases/download/GreatVoyage-v4.4.1/FullNode.jar

Java version:

```bash
$ java -version
openjdk version "1.8.0_292"
OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
```

Documentation referenced:
- https://developers.tron.network/docs/fullnode

Any help will be appreciated.

**Comment by Alexliu007** [comment]
> When attempting to start a Tron Fullnode on the Tesnet it fails with the following error:
> 
> ```shell
> $ java -Xmx2g -XX:+UseConcMarkSweepGC -jar FullNode.jar -c test_net_config.conf
> Exception in thread "main" java.lang.IllegalArgumentException: The address() must be 21 bytes.
> 	at org.tron.common.args.Account.setAddress(Account.java:53)
> 	at org.tron.core.config.args.Args.createAccount(Args.java:851)
> 	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
> 	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
> 	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
> 	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
> 	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
> 	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
> 	at org.tron.core.config.args.Args.getAccountsFromConfig(Args.java:844)
> 	at org.tron.core.config.args.Args.setParam(Args.java:391)
> 	at org.tron.program.FullNode.main(FullNode.java:54)
> ```
> 
> The testnet configuration was found from this github repo:
> 
> * https://github.com/tronprotocol/tron-deployment/blob/master/test_net_config.conf
> 
> The jar was downloaded from the 4.4.0 release:
> 
> * https://github.com/tronprotocol/java-tron/releases/download/GreatVoyage-v4.4.1/FullNode.jar
> 
> Java version:
> 
> ```shell
> $ java -version
> openjdk version "1.8.0_292"
> OpenJDK Runtime Environment (build 1.8.0_292-8u292-b10-0ubuntu1~20.04-b10)
> OpenJDK 64-Bit Server VM (build 25.292-b10, mixed mode)
> ```
> 
> Documentation referenced:
> 
> * https://developers.tron.network/docs/fullnode
> 
> Any help will be appreciated.

Joining the Nile test network requires the use of the Nile branch code:https://github.com/tronprotocol/java-tron/tree/Nile, and config file pls check:https://nileex.io/join/getJoinPage

**Comment by ethan1844** [comment]
Thanks for your contribution to java-tron, this issue will be closed as no update for a long time.

Please feel free to re-open it if you still see the issue, thanks.
