### ISSUE TITLE
Nile testnet sync failed

### ISSUE THREAD

**Issue by Sergey7577** [tronprotocol/tron-deployment#51]
I'm trying to deploy node
branch: Nile
config: from here - https://nileex.io/join/getJoinPage

In logs I get this error:
ERROR [TronJClientWorker-23] [net](SyncService.java:113) Peer /157.245.50.216 sync failed, reason: low: 4577 gt highNoFork: 4519

localhost:8090/wallet/getnodeinfo :

`
{
    "activeConnectCount": 8,
    "beginSyncNum": 5480,
    "block": "Num:5500,ID:000000000000157cd568dc47f0fc5671af41f1bd8cfe2faa73e57b18f2a1affe",
    "cheatWitnessInfoMap": {},
    "configNodeInfo": {
        "activeNodeSize": 1,
        "allowAdaptiveEnergy": 0,
        "allowCreationOfContracts": 0,
        "backupListenPort": 10001,
        "backupMemberSize": 0,
        "backupPriority": 8,
        "codeVersion": "4.4.2",
        "dbVersion": 2,
        "discoverEnable": true,
        "listenPort": 18888,
        "maxConnectCount": 30,
        "maxTimeRatio": 5.0,
        "minParticipationRate": 15,
        "minTimeRatio": 0.0,
        "p2pVersion": "201910292",
        "passiveNodeSize": 0,
        "sameIpMaxConnectCount": 2,
        "sendNodeSize": 0,
        "supportConstant": true,
        "versionNum": "16334"
    },
    "currentConnectCount": 8,
    "machineInfo": {
        "cpuCount": 12,
        "cpuRate": 0.0,
        "deadLockThreadCount": 0,
        "deadLockThreadInfoList": [],
        "freeMemory": 14163013632,
        "javaVersion": "1.8.0_311",
        "jvmFreeMemory": 5872730448,
        "jvmTotalMemory": 7618953216,
        "memoryDescInfoList": [
            {
                "initSize": 2555904,
                "maxSize": 251658240,
                "name": "Code Cache",
                "useRate": 0.09647572835286458,
                "useSize": 24278912
            },
            {
                "initSize": 0,
                "maxSize": -1,
                "name": "Metaspace",
                "useRate": 0.9702590521714443,
                "useSize": 50742344
            },
            {
                "initSize": 0,
                "maxSize": 1073741824,
                "name": "Compressed Class Space",
                "useRate": 0.005647137761116028,
                "useSize": 6063568
            },
            {
                "initSize": 134742016,
                "maxSize": 2793406464,
                "name": "PS Eden Space",
                "useRate": 0.5962491651197096,
                "useSize": 1665566272
            },
            {
                "initSize": 22020096,
                "maxSize": 32505856,
                "name": "PS Survivor Space",
                "useRate": 0.37054246471774194,
                "useSize": 12044800
            },
            {
                "initSize": 358088704,
                "maxSize": 5714214912,
                "name": "PS Old Gen",
                "useRate": 0.012007195573956039,
                "useSize": 68611696
            }
        ],
        "osName": "Linux 4.4.0-19041-Microsoft",
        "processCpuRate": 0.0,
        "threadCount": 132,
        "totalMemory": 34279370752
    },
    "passiveConnectCount": 0,
    "peerList": [
        {
            "active": true,
            "avgLatency": 0.0,
            "blockInPorcSize": 0,
            "connectTime": 1642774711619,
            "disconnectTimes": 0,
            "headBlockTimeWeBothHave": 0,
            "headBlockWeBothHave": "Num:0,ID:0000000000000000d698d4192c56cb6be724a558448e2684802de4d6cd8690dc",
            "host": "103.9.231.76",
            "inFlow": 0,
            "lastBlockUpdateTime": 1642774711764,
            "lastSyncBlock": "",
            "localDisconnectReason": "",
            "needSyncFromPeer": true,
            "needSyncFromUs": false,
            "nodeCount": 21,
            "nodeId": "391d9cfa847629c02ce340f7aa868cbb6c565b5e7a38e38ae8acfcdb5b901cc9ee0777c4f95273426251ee1c1256803e321433ca3798c111cdc2a572b7ae2c3f",
            "port": 18888,
            "remainNum": 0,
            "remoteDisconnectReason": "",
            "score": 126,
            "syncBlockRequestedSize": 0,
            "syncFlag": false,
            "syncToFetchSize": 0,
            "syncToFetchSizePeekNum": -1,
            "unFetchSynNum": 0
        },
        {
            "active": true,
            "avgLatency": 23.0,
            "blockInPorcSize": 1,
            "connectTime": 1642774675467,
            "disconnectTimes": 0,
            "headBlockTimeWeBothHave": 0,
            "headBlockWeBothHave": "Num:5499,ID:000000000000157bf1fc1d059d35bad0102ceb942a33880d3d1ae7d721598e87",
            "host": "95.217.88.118",
            "inFlow": 593554,
            "lastBlockUpdateTime": 1642774711963,
            "lastSyncBlock": "",
            "localDisconnectReason": "",
            "needSyncFromPeer": true,
            "needSyncFromUs": false,
            "nodeCount": 21,
            "nodeId": "bf197c1e0d651a67a82dcddf4e759c627d910f9e6b612a04c92226553bb732f677db9bed70db208ea19922a4fe997a143135edb4bc0440788d80e6bdff47ec46",
            "port": 18888,
            "remainNum": 18254841,
            "remoteDisconnectReason": "",
            "score": 260,
            "syncBlockRequestedSize": 0,
            "syncFlag": false,
            "syncToFetchSize": 2500,
            "syncToFetchSizePeekNum": 5501,
            "unFetchSynNum": 18254841
        },
        {
            "active": true,
            "avgLatency": 51.0,
            "blockInPorcSize": 1,
            "connectTime": 1642774675487,
            "disconnectTimes": 0,
            "headBlockTimeWeBothHave": 0,
            "headBlockWeBothHave": "Num:5499,ID:000000000000157bf1fc1d059d35bad0102ceb942a33880d3d1ae7d721598e87",
            "host": "49.12.196.84",
            "inFlow": 577445,
            "lastBlockUpdateTime": 1642774711963,
            "lastSyncBlock": "",
            "localDisconnectReason": "",
            "needSyncFromPeer": true,
            "needSyncFromUs": false,
            "nodeCount": 21,
            "nodeId": "46d311417f50ef724acf08f08a598fcebf0dbd8e9ec581a2fbb2c7c3fe1e7b0e192ce51c0d0f10a28e0a7e5e07f1ee5418a98873aae2f3c8205d9323598d2654",
            "port": 18888,
            "remainNum": 23159313,
            "remoteDisconnectReason": "",
            "score": 260,
            "syncBlockRequestedSize": 0,
            "syncFlag": false,
            "syncToFetchSize": 2500,
            "syncToFetchSizePeekNum": 5501,
            "unFetchSynNum": 23159313
        },
        {
            "active": true,
            "avgLatency": 62.0,
            "blockInPorcSize": 1,
            "connectTime": 1642774675504,
            "disconnectTimes": 0,
            "headBlockTimeWeBothHave": 0,
            "headBlockWeBothHave": "Num:5499,ID:000000000000157bf1fc1d059d35bad0102ceb942a33880d3d1ae7d721598e87",
            "host": "161.35.23.57",
            "inFlow": 558982,
            "lastBlockUpdateTime": 1642774711963,
            "lastSyncBlock": "",
            "localDisconnectReason": "",
            "needSyncFromPeer": true,
            "needSyncFromUs": false,
            "nodeCount": 21,
            "nodeId": "1f2459c9513949c11b99acbcc8f594dbc93ac2d14ed95bcfbe30a49a2e5b7b9e523742f0543722e94230d557172c5c1a70caa7b7589d28aa88c61c9e26c3de37",
            "port": 18888,
            "remainNum": 23109055,
            "remoteDisconnectReason": "",
            "score": 256,
            "syncBlockRequestedSize": 0,
            "syncFlag": false,
            "syncToFetchSize": 2500,
            "syncToFetchSizePeekNum": 5501,
            "unFetchSynNum": 23109055
        },
        {
            "active": true,
            "avgLatency": 69.0,
            "blockInPorcSize": 1,
            "connectTime": 1642774675510,
            "disconnectTimes": 0,
            "headBlockTimeWeBothHave": 0,
            "headBlockWeBothHave": "Num:5499,ID:000000000000157bf1fc1d059d35bad0102ceb942a33880d3d1ae7d721598e87",
            "host": "142.93.109.129",
            "inFlow": 542270,
            "lastBlockUpdateTime": 1642774711963,
            "lastSyncBlock": "",
            "localDisconnectReason": "",
            "needSyncFromPeer": true,
            "needSyncFromUs": false,
            "nodeCount": 21,
            "nodeId": "40ed0a033cfe3d4fab84adf9be6307315ced88c24a93734e36d352ba9ab7ecde1e91fdbed6de9a78f1d04eb9c010464e57d44207493f1bda8f7859fe91bce4f7",
            "port": 18888,
            "remainNum": 23159313,
            "remoteDisconnectReason": "",
            "score": 255,
            "syncBlockRequestedSize": 0,
            "syncFlag": false,
            "syncToFetchSize": 2500,
            "syncToFetchSizePeekNum": 5501,
            "unFetchSynNum": 23159313
        },
        {
            "active": true,
            "avgLatency": 135.0,
            "blockInPorcSize": 1,
            "connectTime": 1642774679119,
            "disconnectTimes": 0,
            "headBlockTimeWeBothHave": 0,
            "headBlockWeBothHave": "Num:5499,ID:000000000000157bf1fc1d059d35bad0102ceb942a33880d3d1ae7d721598e87",
            "host": "47.253.34.98",
            "inFlow": 505918,
            "lastBlockUpdateTime": 1642774711963,
            "lastSyncBlock": "",
            "localDisconnectReason": "",
            "needSyncFromPeer": true,
            "needSyncFromUs": false,
            "nodeCount": 21,
            "nodeId": "4132fbdd5895baafc4f2eb39a0032909f1414e7ee8fd506e97827403bead1c5f77b7d974c96c4a34a8828ffa7f9d60ac4ebfd1a066fef43780906d87921cdad4",
            "port": 18888,
            "remainNum": 23159127,
            "remoteDisconnectReason": "",
            "score": 247,
            "syncBlockRequestedSize": 0,
            "syncFlag": false,
            "syncToFetchSize": 2686,
            "syncToFetchSizePeekNum": 5501,
            "unFetchSynNum": 23159127
        },
        {
            "active": true,
            "avgLatency": 190.0,
            "blockInPorcSize": 1,
            "connectTime": 1642774682766,
            "disconnectTimes": 0,
            "headBlockTimeWeBothHave": 0,
            "headBlockWeBothHave": "Num:5499,ID:000000000000157bf1fc1d059d35bad0102ceb942a33880d3d1ae7d721598e87",
            "host": "47.252.17.40",
            "inFlow": 473700,
            "lastBlockUpdateTime": 1642774711963,
            "lastSyncBlock": "",
            "localDisconnectReason": "",
            "needSyncFromPeer": true,
            "needSyncFromUs": false,
            "nodeCount": 21,
            "nodeId": "af38266d87db3847535a93adeea6a1aa5189f351be15eb9898d57b9c9dd2f748189d6a1f230879e7c9a560e1fa4fa9341b4b2d664d08dcc52f68ef61c6a00946",
            "port": 18888,
            "remainNum": 23158716,
            "remoteDisconnectReason": "",
            "score": 247,
            "syncBlockRequestedSize": 0,
            "syncFlag": false,
            "syncToFetchSize": 3097,
            "syncToFetchSizePeekNum": 5501,
            "unFetchSynNum": 23158716
        },
        {
            "active": true,
            "avgLatency": 1859.0,
            "blockInPorcSize": 1,
            "connectTime": 1642774693728,
            "disconnectTimes": 0,
            "headBlockTimeWeBothHave": 0,
            "headBlockWeBothHave": "Num:5499,ID:000000000000157bf1fc1d059d35bad0102ceb942a33880d3d1ae7d721598e87",
            "host": "116.66.214.215",
            "inFlow": 304536,
            "lastBlockUpdateTime": 1642774711963,
            "lastSyncBlock": "",
            "localDisconnectReason": "",
            "needSyncFromPeer": true,
            "needSyncFromUs": false,
            "nodeCount": 21,
            "nodeId": "3b1f4d102b125184f5076e4acc13e1998b9d901ec00d4abbb559d39dca711e30ac78fb7908e148a64c996024d39c8606ecb5be07aa5a846d7191d9511364d49d",
            "port": 18888,
            "remainNum": 1619871,
            "remoteDisconnectReason": "",
            "score": 243,
            "syncBlockRequestedSize": 0,
            "syncFlag": false,
            "syncToFetchSize": 3019,
            "syncToFetchSizePeekNum": 5501,
            "unFetchSynNum": 1619871
        }
    ],
    "solidityBlock": "Num:5482,ID:000000000000156a627c60226a540b9794829bfcb73d8561e3ec2cc9cc9af382",
    "totalFlow": 3556405
}
`
Could you please tell me how to deploy node without errors?

**Comment by nekulin** [comment]
The second day I can't synchronize the node

**Comment by Omo-Coc** [comment]
I think you need to use backup data to solve this issue, you can find it here: https://nileex.io/join/getJoinPage
