### ISSUE TITLE
why test_net_config.conf was used  `type = mainnet`

### ISSUE THREAD

**Issue by sonpython** [tronprotocol/tron-deployment#7]
Hi,

I trying deploy fullnode on testnet using this script 

```
wget https://raw.githubusercontent.com/tronprotocol/TronDeployment/master/deploy_tron.sh -O deploy_tron.sh
bash deploy_tron.sh --app FullNode --net testnet
```

When I check the config file at `/home/ubuntu/FullNode/test_net_config.conf ` I saw that it was config to use mainnet as bellow

```
net {
  type = mainnet
  # type = testnet
}
```

**Comment by CooperLee123** [comment]
I am also confused, have you solved the problem?

**Comment by sonpython** [comment]
yes, please take a look here https://github.com/tronprotocol/TronDeployment/pull/1

**Comment by kookiekrak** [comment]
Please dont switch type = testnet.

testnet was deprecated and it will break your build.
