### ISSUE TITLE
TLLM21wteSPs4hKjbxgmH1L6poyMjeTbHm

### ISSUE THREAD

**Issue by 09139626334** [tronprotocol/tron-deployment#81]
wallet> GenerateAddress { "address": "TU6JdEDQGPus64LTMksvnxF2cv4FQrXPCa", "privateKey": "b1ba1db577a36421924a87026cda27523851c6e88123d0a0a1def9a974376176" } #59

**Comment by Balmasexy** [comment]
> wallet> GenerateAddress { "address": "TU6JdEDQGPus64LTMksvnxF2cv4FQrXPCa", "privateKey": "b1ba1db577a36421924a87026cda27523851c6e88123d0a0a1def9a974376176" } #59

**Comment by Balmasexy** [comment]
Transfer to this wallet

**Comment by srbaeza-ai** [comment]
Hopefully

**Comment by srbaeza-ai** [comment]
const { exec } = require('child_process');

// Function to restart the server
function restartServer() {
  const appNameOrId = 'my-app'; // Replace 'my-app' with your PM2 app name or ID
  exec(`pm2 restart ${appNameOrId}`, (error, stdout, stderr) => {
    if (error) {
      console.error(`Error restarting server: ${error.message}`);
      return;
    }
    if (stderr) {
      console.error(`Stderr: ${stderr}`);
      return;
    }
    console.log(`Server restarted successfully. Output: ${stdout}`);
  });
}

// Trigger the restart function
restartServer();
