### ISSUE TITLE
TRC-20 USDT Test Token in not showing Nile Testnet.

### ISSUE THREAD

**Issue by Ong11-git** [tronprotocol/tron-deployment#86]
I have been developing an application that transfers TRC-20 USDT Token from one address to another address with an integrated Tronlink Wallet. However, in order to make a test of the application, I needed a Test token. I also received a test token but the token is not displaying in the TronLink Wallet.

How to solve this problem? Kindly, Provide me with valid articles or references.

**Comment by ferdinand026** [comment]
@Ong11-git Tronlink does not support adding tokens of Nile testnet, but support tokens of Shasta testnet. So you can switch to shasta testnet for testing, or using nile tronscan to transferring tokens of nile testnet instead.

**Comment by Ong11-git** [comment]
@ferdinand026 Thanks I will try it.

**Comment by Ong11-git** [comment]
@ferdinand026 i tried with shasta Test but USDT enable to add in my wallet. contract address "TG3XXyExBkPp9nzdajDZsozEu4BkaSJozs"

**Comment by ferdinand026** [comment]
@Ong11-git Sorry, Tronlink does not support adding tokens of Shasta testnet, but support tokens of Nile testnet. And would  you mind share the trc20 token address?

**Comment by Ong11-git** [comment]
@ferdinand026 Actually, I am trying to send a TRC-20 USDT token from one address to another address and I want to add test TRC-20 USDT in Any Test Net(Nile/Shasta) for testing purposes. The following things that I am not able to perform.
1. Not Able to Add Token into Tronlink Wallet in any Test net(Nile/Shasta)
2. Not Able to See my received Test Token in my Wallet.
What Should I do now?
if you have any references kindly provide me. I Need Help.
Thanks in Advance.

**Comment by ferdinand026** [comment]
> @ferdinand026 Actually, I am trying to send a TRC-20 USDT token from one address to another address and I want to add test TRC-20 USDT in Any Test Net(Nile/Shasta) for testing purposes. The following things that I am not able to perform.
> 
> 1. Not Able to Add Token into Tronlink Wallet in any Test net(Nile/Shasta)
> 2. Not Able to See my received Test Token in my Wallet.
> 3. Not Reflected TRC-20 USDT in Nile test Net.
>    What Should I do now?
>    if you have any references kindly provide me. I Need Help.
>    Thanks in Advance.

First, only tokens on Nile testnet can be added into tronlink chrome extension, and tronlink app does not support nile testnet now.
This is the guide of [trc20 with tronlink](https://developers.tron.network/docs/issuing-trc20-tokens-tutorial)

**Comment by Ong11-git** [comment]
> > @ferdinand026 Actually, I am trying to send a TRC-20 USDT token from one address to another address and I want to add test TRC-20 USDT in Any Test Net(Nile/Shasta) for testing purposes. The following things that I am not able to perform.
> > 
> > 1. Not Able to Add Token into Tronlink Wallet in any Test net(Nile/Shasta)
> > 2. Not Able to See my received Test Token in my Wallet.
> > 3. Not Reflected TRC-20 USDT in Nile test Net.
> >    What Should I do now?
> >    if you have any references kindly provide me. I Need Help.
> >    Thanks in Advance.
> 
> First, only tokens on Nile testnet can be added into tronlink chrome extension, and tronlink app does not support nile testnet now. And this is the guide of [trc20 with tronlink](https://developers.tron.network/docs/issuing-trc20-tokens-tutorial).

How to do it off-chain?

**Comment by ferdinand026** [comment]
I will suggest you to follow the steps of issuing a trc20 token on Nile testnet of the [guide](https://developers.tron.network/docs/issuing-trc20-tokens-tutorial), including record on Tronscan, add tokens to tronlink.
